# Generated by Django 4.2.13 on 2026-06-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('securities_abbreviation', models.CharField(max_length=50, verbose_name='證券簡稱')),
                ('securities_code', models.CharField(max_length=20, unique=True, verbose_name='證券代號')),
                ('issuer', models.CharField(max_length=100, verbose_name='發行人')),
                ('target_index', models.CharField(max_length=200, verbose_name='標的指數')),
                ('management_fee', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='經理費(%)')),
                ('custody_fee', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='保管費(%)')),
                ('dividend_frequency', models.CharField(choices=[('monthly', '每月'), ('quarterly', '每季'), ('semi_annual', '每半年'), ('annual', '每年')], max_length=20, verbose_name='配息頻率')),
                ('dividend_bank', models.CharField(max_length=100, verbose_name='配息銀行')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ETF',
                'verbose_name_plural': 'ETF',
                'ordering': ['securities_code'],
            },
        ),
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_dividend_date', models.DateField(verbose_name='除息日')),
                ('dividend_amount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='配息金額(元)')),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='除息日收盤價(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_records', to='etf.etf', verbose_name='ETF')),
            ],
            options={
                'verbose_name': '歷史配息紀錄',
                'verbose_name_plural': '歷史配息紀錄',
                'ordering': ['-ex_dividend_date'],
                'unique_together': {('etf', 'ex_dividend_date')},
            },
        ),
    ]
