# Generated by Django 5.2.12 on 2026-06-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etf', '0002_etf_holdings_etf_latest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendrecord',
            name='annualized_yield_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, verbose_name='年化配息率(%)'),
        ),
    ]
